name: jason
favicon: null
layout_spectrum: 0.34622950246557593
typography_spectrum: 0.535779531346634
title: Jason Putorti
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.15964608965441585
  lightness: 0.2045409670099616
  saturation: 0.39944053371436894
  rhythmicContrast: 0.8290240145288408
purpose: []
